### ISSUE TITLE
Fix Codacy

### ISSUE THREAD

**Issue by jrddunbr** [eln2/eln2#113]
The Codacy CI plugin seems to be broken, the CI build takes forever, and then Codacy times out after two minutes saying it can't find coverage data because it's still building. The Codacy UI is all sorts of messed up and I can't even get it to retry successfully after the build is done, so I just removed this for the time being until we can fix it.

```yml
            -   name: Generate coverage reports
                run: ./gradlew jacocoTestReport

            -   name: codacy-coverage-reporter
                uses: codacy/codacy-coverage-reporter-action@0.1.0
                with:
                    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
```
